# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        exclude: mobipick_description/config/joint_limits.yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: &excludes |
          (?x)^(
              .*\.blend|
              .*\.dae|
              .*\.mtl|
              .*\.obj|
              .*\.pgm|
              .*\.step|
              .*\.stl
          )$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        exclude: *excludes
      - id: trailing-whitespace
        exclude: *excludes

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/detailyang/pre-commit-shell.git
    rev: v1.0.6
    hooks:
    - id: shell-lint
      args: [--external-sources]

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
    - id: markdownlint

  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    - id: dockerfilelint
